### ISSUE TITLE
What's the inputs of GAN-TTS?

### ISSUE THREAD

**Issue by Alexander-flyer** [r9y9/gantts#12]
I run the tts_demo.sh before, and it works well.
I noticed that '.lab' file is one of input for function"tts_from_label()" 
My question is what should I do if I want producing a '.wav' file by a string of char.
Should I convert the string to a '.lab' file?
If that means I should build a front-end containing a trained module to deal with the string? 
Thx!

**Comment by r9y9** [comment]
The input is full-context label file (.lab). You need to generate labels by frontend tools such as Festival. See https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/build_your_own_voice/s1#prepare-labels and https://github.com/CSTR-Edinburgh/merlin/issues/28.

If you are interested in a trainable module, then I would recommend an end-to-end model such as Tacotron2 or DeepVoice3. The input of these models is a raw text. See https://github.com/r9y9/deepvoice3_pytorch for example.

**Comment by Alexander-flyer** [comment]
Thanks for your response!

**Comment by r9y9** [comment]
Closing this. Feel free to reopen if you want to continue the discussion, or create a new issue.

**Comment by mrgloom** [comment]
@r9y9 Did you mean `prepare_labels_from_txt.sh` from merlin project?

```
find . -name "prepare_labels_from_txt.sh"
./egs/nick_hurricane/s1/scripts/prepare_labels_from_txt.sh
./egs/mandarin_voice/s1/scripts/prepare_labels_from_txt.sh
./egs/speaker_adaptation/s1/scripts/prepare_labels_from_txt.sh
./egs/slt_arctic/s1/scripts/prepare_labels_from_txt.sh
./egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh
./egs/fls_blizzard2017/s1/scripts/prepare_labels_from_txt.sh
./misc/scripts/alignment/state_align/prepare_labels_from_txt.sh
```

Suppose we want to use:
```
./egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh
Usage: ./scripts/prepare_labels_from_txt.sh <path_to_text_dir> <path_to_lab_dir> <path_to_global_conf_file>
```

Not sure which config to use:
```
find ./egs/build_your_own_voice/ -name "*conf*"
./egs/build_your_own_voice//s1/04_prepare_conf_files.sh
./egs/build_your_own_voice//s1/scripts/prepare_config_files_for_synthesis.sh
./egs/build_your_own_voice//s1/scripts/prepare_config_files.sh
./egs/build_your_own_voice//s1/conf
./egs/build_your_own_voice//s1/conf/keras/duration_demo.conf
./egs/build_your_own_voice//s1/conf/keras/acoustic_demo.conf
./egs/build_your_own_voice//s1/conf/general/duration_demo.conf
./egs/build_your_own_voice//s1/conf/general/acoustic_demo.conf
./egs/build_your_own_voice//s1/conf/logging_config.conf
```


My dummy dataset:
```
tree my_dataset
my_dataset
├── arctic_a0001.wav
└── sentences.txt

cat my_dataset/sentences.txt
( arctic_a0001 "Author of the danger trail, Philip Steels, etc." )
```

Looking at steps in file `./egs/build_your_own_voice/s1/scripts/prepare_labels_from_txt.sh`:

```
python misc/scripts/frontend/utils/genScmFile.py
Usage: python genScmFile.py <in_txt_dir/in_txt_file> <out_utt_dir> <out_scm_file> <out_file_id_list>

python misc/scripts/frontend/utils/genScmFile.py my_dataset/sentences.txt my_dataset/temp my_dataset/temp/out_scm_file my_dataset/temp/out_file_id_list
creating a scheme file from text file
```

```
my_dataset/
├── arctic_a0001.wav
├── sentences.txt
└── temp
    ├── out_file_id_list
    └── out_scm_file
```

Looks it's just prepare some meta data:

```
cat my_dataset/temp/out_file_id_list
arctic_a0001

cat my_dataset/temp/out_scm_file
(utt.save (utt.synth (Utterance Text "Author of the danger trail, Philip Steels, etc." )) "my_dataset/temp/arctic_a0001.utt")
```

I have separately compiled festival:
```
./festival/bin/festival --version
./festival/bin/festival: Festival Speech Synthesis System: 2.4:release December 2014
```

Obtain `*.utt` file:
```
./festival/festival/bin/festival -b my_dataset/temp/out_scm_file
```

```
my_dataset/
├── arctic_a0001.wav
├── sentences.txt
└── temp
    ├── arctic_a0001.utt
    ├── out_file_id_list
    └── out_scm_file
```

```
cat my_dataset/temp/arctic_a0001.utt | head -n 40
EST_File utterance
DataType ascii
version 2
EST_Header_End
Features max_id 149 ; type Text ; iform "\"Author of the danger trail, Philip Steels, etc.\"" ;
Stream_Items
1 id _1 ; name Author ; whitespace "" ; prepunctuation "" ;
2 id _2 ; name of ; whitespace " " ; prepunctuation "" ;
3 id _3 ; name the ; whitespace " " ; prepunctuation "" ;
4 id _4 ; name danger ; whitespace " " ; prepunctuation "" ;
5 id _5 ; name trail ; punc , ; whitespace " " ; prepunctuation "" ;
6 id _6 ; name Philip ; whitespace " " ; prepunctuation "" ;
7 id _7 ; name Steels ; punc , ; whitespace " " ; prepunctuation "" ;
8 id _8 ; name etc ; punc "0" ; whitespace " " ; prepunctuation "" ;
9 id _18 ; name etc ; pos_index 8 ; pos_index_score 0 ; pos nn ; phr_pos n ; pbreak_index 0 ; pbreak_index_score 0 ; pbreak B ; blevel 3 ;
10 id _16 ; name Steels ; pos_index 8 ; pos_index_score 0 ; pos nnp ; phr_pos n ; phrase_score -0.67725 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
11 id _17 ; name , ; pos_index 13 ; pos_index_score 0 ; pos punc ; phr_pos punc ; phrase_score -7.13934 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
12 id _15 ; name Philip ; pos_index 8 ; pos_index_score 0 ; pos nnp ; phr_pos n ; phrase_score -5.2298 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
13 id _13 ; name trail ; pos_index 8 ; pos_index_score 0 ; pos nn ; phr_pos n ; phrase_score -0.67725 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak B ;
14 id _14 ; name , ; pos_index 13 ; pos_index_score 0 ; pos punc ; phr_pos punc ; phrase_score -7.13934 ; pbreak_index 0 ; pbreak_index_score 0 ; pbreak B ; blevel 3 ;
15 id _12 ; name danger ; pos_index 8 ; pos_index_score 0 ; pos nn ; phr_pos n ; phrase_score -4.65861 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
16 id _11 ; name the ; pos_index 2 ; pos_index_score 0 ; pos dt ; phr_pos dt ; phrase_score -4.8828 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
17 id _10 ; name of ; pos_index 9 ; pos_index_score 0 ; pos of ; phr_pos of ; phrase_score -4.75518 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
18 id _9 ; name Author ; pos_index 8 ; pos_index_score 0 ; pos nn ; phr_pos n ; phrase_score -7.42703 ; pbreak_index 1 ; pbreak_index_score 0 ; pbreak NB ;
19 id _19 ; name B ;
20 id _20 ; name B ;
21 id _21 ; name syl ; stress 1 ;
22 id _23 ; name syl ; stress 0 ;
23 id _26 ; name syl ; stress 1 ;
24 id _29 ; name syl ; stress 0 ;
25 id _32 ; name syl ; stress 1 ;
26 id _36 ; name syl ; stress 0 ;
27 id _39 ; name syl ; stress 1 ;
28 id _44 ; name syl ; stress 1 ;
29 id _47 ; name syl ; stress 0 ;
30 id _51 ; name syl ; stress 1 ;
31 id _57 ; name syl ; stress 1 ;
32 id _60 ; name syl ; stress 1 ;
33 id _63 ; name syl ; stress 0 ;
34 id _66 ; name syl ; stress 0 ;
```

From `*.utt` to `*.lab`:
```
./misc/scripts/frontend/festival_utt_to_lab/make_labels
make_labels <labels_dir> <utts_dir> <dumpfeats> <scripts>

./misc/scripts/frontend/festival_utt_to_lab/make_labels my_dataset/temp/lab_dir/ my_dataset/temp/utt_dir/ ./festival/festival/examples/dumpfeats ./misc/scripts/frontend/festival_utt_to_lab
```

```
my_dataset
├── arctic_a0001.wav
├── sentences.txt
└── temp
    ├── arctic_a0001.lab
    │   ├── full
    │   │   └── *.lab
    │   └── mono
    │       └── *.lab
    ├── arctic_a0001.utt
    ├── lab_dir
    │   ├── full
    │   │   └── arctic_a0001.lab
    │   ├── mono
    │   │   └── arctic_a0001.lab
    │   └── tmp
    ├── out_file_id_list
    ├── out_scm_file
    └── utt_dir
        └── arctic_a0001.utt
```

Looks like *.lab is some binary format.

I have checked it without *.wav file and seems it works too:
```

python misc/scripts/frontend/utils/genScmFile.py my_dataset/sentences.txt my_dataset/temp my_dataset/temp/out_scm_file my_dataset/temp/out_file_id_list
./festival/festival/bin/festival -b my_dataset/temp/out_scm_file
./misc/scripts/frontend/festival_utt_to_lab/make_labels my_dataset/temp/ my_dataset/temp/ ./festival/festival/examples/dumpfeats ./misc/scripts/frontend/festival_utt_to_lab
```

```
tree my_dataset
my_dataset
├── sentences.txt
└── temp
    ├── arctic_a0001.utt
    ├── full
    │   └── arctic_a0001.lab
    ├── mono
    │   └── arctic_a0001.lab
    ├── out_file_id_list
    ├── out_scm_file
    └── tmp
```

Then I have tried to generate `*.wav` with obtained `*.lab` file:

Do I need to use mean, std, min, max files from `./data/cmu_arctic_tts_order59/` ?
```
./data/cmu_arctic_tts_order59/X_acoustic_data_min.npy
./data/cmu_arctic_tts_order59/Y_duration_data_var.npy
./data/cmu_arctic_tts_order59/X_duration_data_max.npy
./data/cmu_arctic_tts_order59/Y_acoustic_data_mean.npy
./data/cmu_arctic_tts_order59/X_acoustic_data_max.npy
./data/cmu_arctic_tts_order59/Y_acoustic_data_var.npy
./data/cmu_arctic_tts_order59/Y_duration_data_mean.npy
./data/cmu_arctic_tts_order59/X_duration_data_min.npy
```

I have modified this code: https://github.com/r9y9/gantts/blob/7f7eb8555afc5810087e6fd9e4243fb3676babc1/evaluation_tts.py#L316

Like:
```
    lab_filepath = 'my_dataset/temp/full/arctic_a0001.lab'
    wav_filepath = 'my_dataset/temp/full/arctic_a0001.wav'

    waveform, mgc, lf0, vuv, bap = tts_from_label(
        models, lab_filepath, X_min, X_max, Y_mean, Y_std,
        apply_duration_model=not disable_duration_gen,
        post_filter=post_filter, fs=fs)
    wavfile.write(wav_filepath, fs, waveform.astype(np.int16))
```

But get error in duration prediction:
Here https://github.com/r9y9/gantts/blob/7f7eb8555afc5810087e6fd9e4243fb3676babc1/evaluation_tts.py#L177 duration_predicted.shape is (36, 5)

```
Command line args:
 {'--disable-duraton-gen': False,
 '--fs': '16000',
 '--help': False,
 '--post-filter': False,
 '<acoustic_checkpoint>': './checkpoints/experiment_tts/tts_acoustic/baseline/checkpoint_epoch50_Generator.pth',
 '<data_dir>': './data/cmu_arctic_tts_order59',
 '<duration_checkpoint>': './checkpoints/experiment_tts/tts_duration/baseline/checkpoint_epoch100_Generator.pth',
 '<labels_dir>': './nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/',
 '<outputs_dir>': './generated/experiment_tts/duration_acousic/baseline'}
Load checkpoint from: ./checkpoints/experiment_tts/tts_acoustic/baseline/checkpoint_epoch50_Generator.pth
Load checkpoint from: ./checkpoints/experiment_tts/tts_duration/baseline/checkpoint_epoch100_Generator.pth
{'acoustic': SRURNN(
  (gru): SRU(
    (rnn_lst): ModuleList(
      (0): SRUCell(425, 512, dropout=0.2, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (1): SRUCell(1024, 512, dropout=0.2, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (2): SRUCell(1024, 512, dropout=0.2, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (3): SRUCell(1024, 512, dropout=0.2, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (4): SRUCell(1024, 512, dropout=0.2, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (5): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
    )
    (ln_lst): ModuleList()
  )
  (hidden2out): Linear(in_features=1024, out_features=187, bias=True)
  (sigmoid): Sigmoid()
), 'duration': SRURNN(
  (gru): SRU(
    (rnn_lst): ModuleList(
      (0): SRUCell(416, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (1): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (2): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (3): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (4): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
      (5): SRUCell(1024, 512, rnn_dropout=0.2, bidirectional=True, activation=ReLU, rescale=True)
    )
    (ln_lst): ModuleList()
  )
  (hidden2out): Linear(in_features=1024, out_features=5, bias=True)
  (sigmoid): Sigmoid()
)}
/usr/local/lib/python3.6/site-packages/sru/sru_functional.py:114: UserWarning: C++ kernel for SRU CPU inference was not loaded. Use Python version instead.
  warnings.warn("C++ kernel for SRU CPU inference was not loaded. "
<class 'numpy.ndarray'>
duration_predicted.shape (36, 5)
Traceback (most recent call last):
  File "my_evaluation_tts.py", line 332, in <module>
    post_filter=post_filter, fs=fs)
  File "my_evaluation_tts.py", line 197, in tts_from_label
    label_path, duration_model, X_min, X_max, Y_mean, Y_std)
  File "my_evaluation_tts.py", line 179, in gen_duration
    hts_labels.set_durations(duration_predicted)
  File "/usr/local/lib/python3.6/site-packages/nnmnkwii/io/hts.py", line 159, in set_durations
    raise RuntimeError("Unexpected input, maybe")
RuntimeError: Unexpected input, maybe
```

Looks like error comes from here:
https://github.com/r9y9/nnmnkwii/blob/master/nnmnkwii/io/hts.py#L158

**Comment by mrgloom** [comment]
As I can see when run on default dataset:

```
./generated/experiment_tts/duration_acousic/baseline/eval ./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_a0182.lab
duration_predicted.shape (26, 5)
./generated/experiment_tts/duration_acousic/baseline/eval ./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_a0464.lab
duration_predicted.shape (46, 5)
./generated/experiment_tts/duration_acousic/baseline/eval ./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_a0126.lab
duration_predicted.shape (32, 5)
./generated/experiment_tts/duration_acousic/baseline/eval ./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_b0534.lab
duration_predicted.shape (38, 5)
./generated/experiment_tts/duration_acousic/baseline/eval ./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_a0571.lab
duration_predicted.shape (31, 5)
```
