### ISSUE TITLE
ImportError: No module named cuda_functional

### ISSUE THREAD

**Issue by annisaabuhamid** [r9y9/gantts#6]
Hello @r9y9 ,
i have been running the module in python 2.7 and i encountered the following error:  

Traceback (most recent call last):
  File "train.py", line 773, in <module>
    model_g = getattr(gantts.models, hp.generator)(**hp.generator_params)
  File "/home/sasa/nisa/gantts/gantts/models.py", line 150, in __init__
    from cuda_functional import SRU
ImportError: No module named cuda_functional

**Comment by r9y9** [comment]
Try Install https://github.com/taolei87/sru, please.

**Comment by annisaabuhamid** [comment]
Traceback (most recent call last):
  File "train.py", line 828, in <module>
    mse_w=mse_w, mge_w=mge_w)
  File "train.py", line 544, in train_loop
    model_g, generator_input, R, cpu_sorted_lengths)
  File "train.py", line 353, in apply_generator
    y_hat, R, hp.stream_sizes, hp.has_dynamic_features)
  File "/home/sasa/nisa/gantts/gantts/multistream.py", line 120, in multi_stream_mlpg
    y = unit_variance_mlpg(R, x) if v else x
  File "/usr/local/lib/python2.7/dist-packages/nnmnkwii/autograd/_impl/mlpg.py", line 226, in unit_variance_mlpg
    return UnitVarianceMLPG(R)(means)
  File "/usr/local/lib/python2.7/dist-packages/nnmnkwii/autograd/_impl/mlpg.py", line 152, in forward
    out = torch.matmul(self.R, reshaped_means)
  File "/usr/local/lib/python2.7/dist-packages/torch/functional.py", line 217, in matmul
    tensor1_expanded = tensor1.expand(*(expand_batch_portion + tensor1_exp_size[-2:])) \
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66

@r9y9 i got another error after i run ./tts_demo.sh tts_test . So, what is the best solution to fix this error?

**Comment by r9y9** [comment]
dup of https://github.com/r9y9/gantts/issues/3. Try smaller batch size.

**Comment by kindleton** [comment]
Hey @r9y9 , is SRU installation necessary for running TTS demo ?

**Comment by Shikherneo2** [comment]
You could just try using GRU instead of SRU. replace that in hparams.py

**Comment by m1randa** [comment]
I have the same problem with @niccanicci. Can you please help me solve it?
How can we install GRU instead of SRU?

**Comment by Cpruce** [comment]
At line 150 in gantts/models.py, change `from cuda_functional import SRU` to `from sru import SRU`

**Comment by mrgloom** [comment]
`pip install sru` not helped

Replacing `At line 150 in gantts/models.py, change from cuda_functional import SRU to from sru import SRU`
gives an error:
```
  File "/data/my_data/external_projects/gantts/my_env/lib/python3.5/site-packages/sru/sru_functional.py", line 35, in _lazy_load_cuda_kernel
    from cuda_functional import SRU_Compute_GPU
ImportError: No module named 'cuda_functional'
```

**Update:** 
`pip install sru[cuda]` helped

**Comment by yuuSiVo** [comment]
I have same issue 

File "/mnt/c/Users/yuu/Documents/gantts-jp/gantts/models.py", line 150, in __init__
    from cuda_functional import SRU
ImportError: No module named 'cuda_functional'

**Comment by yuuSiVo** [comment]
I installed all cuda enviroment

**Comment by r9y9** [comment]
See https://github.com/asappresearch/sru#examples

Looks like sru changed the module name.

**Comment by coocoorhin** [comment]
> See https://github.com/asappresearch/sru#examples
> 
> Looks like sru changed the module name.

yeah they did changed the module name. also removed "use_relu"
