### ISSUE TITLE
Problem with dataset_loaders

### ISSUE THREAD

**Issue by raghadeepa** [r9y9/gantts#8]
During duration modeling I am facing following issue. Could you please suggest for workaround. 

Traceback (most recent call last):
  File "train.py", line 829, in <module>
    mse_w=mse_w, mge_w=mge_w)
  File "train.py", line 493, in train_loop
    for x, y, lengths in dataset_loaders[phase]:
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 62, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 123, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 123, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 117, in pin_memory_batch
    return batch.pin_memory()
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/tensor.py", line 82, in pin_memory
    return type(self)().set_(storage.pin_memory()).view_as(self)
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/storage.py", line 83, in pin_memory
    allocator = torch.cuda._host_allocator()
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 220, in _host_allocator
    _lazy_init()
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 85, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1503963423183/work/torch/lib/THC/THCGeneral.c:70

**Comment by r9y9** [comment]
Does this happen only with gantts? Are you able to run some of pytorch examples (see https://github.com/pytorch/examples) successfully?

**Comment by r9y9** [comment]
Maybe you can try `pin_memory=False` here: https://github.com/r9y9/gantts/blob/8111e255fb65ded1f0361c18c1a7e5c4c13ad840/hparams.py#L81.

**Comment by raghadeepa** [comment]
pin_memory=False did not help.

I tried with one of the pyTorch Examples (word_language_model). When I run with --cuda enabled, am seeing following error. If I run without cuda, model is being trained. I tried with Cuda 7.5 and Cuda 8.0. Both have the same issue. 

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1503963423183/work/torch/lib/THC/THCGeneral.c line=70 error=11 : invalid argument
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    train_data = batchify(corpus.train, args.batch_size)
  File "main.py", line 81, in batchify
    data = data.cuda()
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 266, in _lazy_new
    _lazy_init()
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 85, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1503963423183/work/torch/lib/THC/THCGeneral.c:70

**Comment by r9y9** [comment]
So please file an issue to the pytorch. I cannot reproduce.

**Comment by raghadeepa** [comment]
Will do it. Thank you.

**Comment by raghadeepa** [comment]
Restarting the server helped to fix the issue. It's really interesting. 👍
